# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-14 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.CharField(choices=[(b'A', b'Animal'), (b'P', b'Plant'), (b'O', b'Other'), (b'U', b'Unknown')], default=b'U', max_length=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_avatars', to='base.Photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_backgrounds', to='base.Photo'),
        ),
    ]
