version: 2
jobs:
  build:
    working_directory: ~/django-multi-form-view
    docker:
      - image: circleci/python:3.6.4-browsers
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Run Tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements.txt
            coverage run demo/manage.py behave
            codecov
